before_script:
  - poetry install
image: registry.gitlab.com/tankerhq/ci/ci-native:latest

stages:
  - build
  - deploy

.proxy:
  variables:
    FETCHPP_TEST_HOST: "httpbin.org"
    FETCHPP_TEST_PROXY: "tinyproxy:8888"
  services:
    - name: registry.gitlab.com/tankerhq/ci/tinyproxy:latest
      alias: tinyproxy

.build:
  stage: build
  extends: .proxy
  except:
    - schedules

build/linux:
  extends: .build
  tags: [linux]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release

build/macos:
  extends: .build
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile macos-release

build/windows:
  extends: .build
  tags: [windows]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile vs2019-release

coverage:
  extends: .proxy
  stage: build
  only:
    - schedules
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release --coverage
    - mv build/gcc8-release/coverage coverage
  tags:
    - linux
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags
    - master
  except:
    - schedules
  script:
    - poetry run python run-ci.py  mirror

pages:
  stage: deploy
  only:
    - schedules
  dependencies:
    - coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux
