version: '2'
services:
    httpbin:
      image: kennethreitz/httpbin
      ports:
        - "80:80"
    ssl_proxy:
      image: fsouza/docker-ssl-proxy
      environment:
        DOMAIN: fetchpp-test.tanker.io
        TARGET_HOST: httpbin
        TARGET_PORT: 80
        SSL_PORT: 443
      ports:
        - '443:443'
    #custom_proxy:
      #image: fsouza/docker-ssl-proxy
      #environment:
        #DOMAIN: fetchpp-test.tanker.io
        #TARGET_HOST: httpbin
        #TARGET_PORT: 80
        #SSL_PORT: 4444
      #ports:
        #- '4444:4444'
