[version]
current = "0.14.0"

regex = '''
  (0.14.0)
  |
  (
    (?P<major>\d+)
    \.
    (?P<minor>\d+)
    \.
    (?P<patch>\d+)
    (
      -
      (?P<lifecycle>alpha|beta|r)
      (?P<release>\d+)
    )?
  )
'''

[git]
message_template = "Bump to v{new_version}"
tag_template = "v{new_version}"

[[file]]
src = "conanfile.py"
search = 'version = "{current_version}"'

[[file]]
src = "libs/fetchpp/include/fetchpp/version.hpp"
search = 'VERSION = "{current_version}"'

[[file]]
src = "libs/fetchpp/include/fetchpp/version.hpp"
search = 'USER_AGENT = "fetchpp/{current_version}"'
