[version]
current = "dev"

regex = '''
  (dev)
  |
  (
    (\d+)
  )
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "conanfile.py"
search = 'version = "{current_version}"'

[[file]]
src = "libs/fetchpp/include/fetchpp/version.hpp"
search = 'VERSION = "{current_version}"'

[[file]]
src = "libs/fetchpp/include/fetchpp/version.hpp"
search = 'USER_AGENT = "fetchpp/{current_version}"'
